version: "2.0"

services:
  node:
    image: chandrastation/evmosakt:v1.0.0
    env:
      - MONIKER=akt_evmos
      - CHAIN_JSON=https://github.com/chalabi2/chain-registry/blob/master/evmos/chain-testnet.json
      - VALIDATE_GENESIS=0
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          size: 100Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1